### PR TITLE
Optimize Perf Metrics (adjust waitForLCP, remove editor-support from head - will be loaded automatically, remove sidekick)

### PR DESCRIPTION
**Pull request by ifahrentholz**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:

- Before: https://develop--xwalk-boilerplate--diva-e-aem.aem.live/ 
- After: https://devmode--xwalk-boilerplate--diva-e-aem.aem.live/

**Checklist:**
- [ ] Tests added/passed
- [ ] Documentation updated
- [ ] PSI Checks passed
- [ ] Test environment works as expected
- [ ] New Block/Feature/Component works on test environment
- [ ] Code reviewed

### CODE REVIEW

**Comment by ifahrentholz** [comment]
@eKrausedivae can you please check this branch out and double check that the boilerplate still works ?

**Comment by eKrausedivae** [comment]
.env file is still in the root directory

**Review by eKrausedivae — CHANGES_REQUESTED** [review]
remove .env file

**Review by eKrausedivae — APPROVED** [review]

**Comment by samuelecalamita** [comment]
fix #14

**Pull request merged**
